name = "DataExemplo"
uuid = "baa560f1-2cfc-4222-8843-5694590054be"
authors = ["Augusto Manzano"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
